name: sotw_multi_logger
description: "Multiple logger wrapper for logger"
version: 0.0.2
repository: https://github.com/sotw-sw/flutter_multi_logger

environment:
  sdk: ^3.10.4

dependencies:
  logger: ^2.6.2
